version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep ; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://muic_vending_machine:postmuic_vending_machinegres@db:5432/muic_vending_machine
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=muic_vending_machine
      - POSTGRES_PASSWORD=muic_vending_machine
      - POSTGRES_DB=muic_vending_machine
    
volumes:
  postgres_data:
    